version: "3"
services:
    app:
        image: ghcr.io/xtrem-max/cuizin-back:main
        container_name: cuizin-back
        tty: true
        ports:
            - "4000:3000"
        env_file:
            - app.env
        networks:
            - "web"
networks:
    web:
        external: true