version: "3"
services:
    app:
        image: ghcr.io/totodore/automate:latest #TODO: Changer le lien de l'image
        container_name: cuizin-back
        tty: true
        ports:
            - "4000:3000"
        env_file:
            - app.env
        networks:
            - "web"
networks:
    web:
        external: true